services:
  - type: web
    name: word-counter
    env: java
    rootDir: backend
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    branch: main
    autoDeploy: true
